spring.application.name=Translator
api.base.url=https://translate.googleapis.com/translate_a/single?client=gtx&dt=t
spring.datasource.url=jdbc:postgresql://localhost:5432/data
spring.datasource.username=fedor
spring.datasource.password=123

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
logging.file.name=application.log
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
